//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMWB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PASSCODE
    {
        public int CM_ID { get; set; }
        public string CM_PHONE { get; set; }
        public string CM_CODE { get; set; }
        public int CM_SENTCOUNT { get; set; }
        public System.DateTime CM_SENTTIME { get; set; }
        public string CM_TYPE { get; set; }
    }
}
