//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMWB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USER
    {
        public string CM_USERID { get; set; }
        public string CM_OPENID { get; set; }
        public string CM_USERNAME { get; set; }
        public string CM_SEX { get; set; }
        public string CM_PHONE { get; set; }
        public string CM_PASSWORD { get; set; }
        public string CM_PICPATH { get; set; }
        public Nullable<System.DateTime> CM_CREATETIME { get; set; }
        public Nullable<int> CM_ISVIP { get; set; }
        public Nullable<System.DateTime> CM_EXPIRINGTIME { get; set; }
        public string CM_TRADE { get; set; }
    }
}
