//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMWB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XMWBEntities : DbContext
    {
        public XMWBEntities()
            : base("name=XMWBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_ADVERT> TB_ADVERT { get; set; }
        public virtual DbSet<TB_ARTICLE> TB_ARTICLE { get; set; }
        public virtual DbSet<TB_CAROUSELFIGURE> TB_CAROUSELFIGURE { get; set; }
        public virtual DbSet<TB_FEEDBACK> TB_FEEDBACK { get; set; }
        public virtual DbSet<TB_KEY> TB_KEY { get; set; }
        public virtual DbSet<TB_LSARTICLE> TB_LSARTICLE { get; set; }
        public virtual DbSet<TB_PASSCODE> TB_PASSCODE { get; set; }
        public virtual DbSet<TB_PAYINFO> TB_PAYINFO { get; set; }
        public virtual DbSet<TB_SENSITIVECODE> TB_SENSITIVECODE { get; set; }
        public virtual DbSet<TB_USER> TB_USER { get; set; }
        public virtual DbSet<TB_XXX> TB_XXX { get; set; }
    }
}
